spring:
  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/jpa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8055