spring:
  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/jpa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: com.jpa.dialect.PostgreSQL9DialectWithoutFK
server:
  port: 8055