spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Csk@513434
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大连接阻塞等待时间,默认 -1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.easyexcel.pojo
# minio文件系统
minio:
  ip: http://127.0.0.1:9000  # 管理端口
  username: minio_root    #登录用户，可以自己创建其他用户
  password: minio_123456
  bucket: "barcode"  #Bucket的名称

# MyBatis SQL打印
logging:
  level:
    com.easyexcel.mapper: debug
server:
  port: 8049

