spring:
  rabbitmq:
    host: 192.168.64.143
    port: 5672
    username: swsk33
    password: 123456
    virtualHost: /
    connectionTimeout: 15000
    publisherConfirmType: correlated
    publisherReturns: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Csk@513434
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大连接阻塞等待时间,默认 -1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: com.easyexcel.pojo
# MyBatis SQL打印
#logging:
#  level:
#    com.easyexcel.mapper: debug
server:
  port: 8050
